# Generated by Django 4.2.7 on 2023-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='text',
            field=models.TextField(),
        ),
    ]
