# Generated by Django 4.2.7 on 2024-02-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0002_alter_words_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='wordsList',
        ),
        migrations.AddField(
            model_name='words',
            name='title',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.DeleteModel(
            name='TestWordsList',
        ),
    ]
